name: 'ðŸ› Bug report'
labels: 'bug'
description: Create a bug report to help us improve

body:
  - type: markdown
    attributes:
      value: |
        **Never report security issues on GitHub or other public channels (Gitter/Twitter/etc.)**
        Follow these instruction to report security issues: https://www.jenkins.io/security/#reporting-vulnerabilities

  - type: textarea
    attributes:
      label: Jenkins and plugins versions report
      description: |
        When reporting a bug, please **try** to provide as much information as possible.

        * Plugin version used.
        * Jenkins version used.
        * Your configuration.
          * Variables configured, names, expressions...
          * Pipeline script (See Pipeline section in README)
        * Build job log
        * Post content received. It can be found in the job execution log. People using GitHub often forget to set the content type in "Manage webhook" when configuring the webhook at GitHub.
        * A `curl` command and its response.
        * Expected result and actual result.

        For easier bug reporting, you can get the full list of plugins with this Groovy script that you can run in **Jenkins > Manage Jenkins > Script Console**:
        ```groovy
        println("Jenkins: ${Jenkins.instance.getVersion()}")
        println("OS: ${System.getProperty('os.name')} - ${System.getProperty('os.version')}")
        println("Java: ${System.getProperty('java.version')} - ${System.getProperty('java.vm.vendor')} (${System.getProperty('java.vm.name')})")
        println "---"

        Jenkins.instance.pluginManager.plugins
          .collect()
          .sort { it.getShortName() }
          .each {
            plugin -> println("${plugin.getShortName()}:${plugin.getVersion()}")
          }
        return
        ```


        You may also have a look at the test cases as they should answer the most common questions:
        
          https://github.com/jenkinsci/generic-webhook-trigger-plugin/tree/master/src/test/resources/org/jenkinsci/plugins/gwt/bdd

        If you are fiddling with expressions, you may want to checkout:

        * [This JSONPath site](http://jsonpath.herokuapp.com/)
        * [This XPath site](http://www.freeformatter.com/xpath-tester.html)
        * [This regexp site](https://jex.im/regulex/)

        A Curl command can look something like this:
        ```
        curl -v -H "Content-Type: application/json" -X POST -d '{ "app":{ "name":"GitHub API", "url":"http://developer.github.com/v3/oauth/" }}' http://localhost:8080/jenkins/generic-webhook-trigger/invoke?token=sometoken
        ```
